# Project: Matriz Tirabuzon
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Matriz\ tirabuzon.o"
LINKOBJ  = "Matriz tirabuzon.o"
LIBS     = -L"C:/Users/Public/Documents/Dev-Cpp/MinGW64/lib32" -L"C:/Users/Public/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"C:/Users/Public/Documents/Dev-Cpp/MinGW64/include" -I"C:/Users/Public/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Public/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Public/Documents/Dev-Cpp/MinGW64/include" -I"C:/Users/Public/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Public/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Public/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Matriz Tirabuzon.exe"
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"Matriz\ tirabuzon.o": Matriz\ tirabuzon.c
	$(CC) -c "Matriz tirabuzon.c" -o "Matriz tirabuzon.o" $(CFLAGS)
